version: "3.3"
services:
  angular-app:
    image: ihebghr/angular-app:latest
    ports:
      - "4200:80"
    depends_on:
      - spring-boot-app

  spring-boot-app:
    image: ihebghr/springboot-app:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure # Très important : redémarre si MySQL n'est pas prêt
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - demo_data:/var/lib/mysql

volumes:
  demo_data: